apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-dbcreation-script
data: 
  mysql_usermgmt.sql: |- # run this script at the pod start
    DROP DATABASE IF EXISTS usermgmt;
    CREATE DATABASE usermgmt; 