apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: karpenter
  labels:
    kubernetes.io/os: linux
    deployment.group: karpenter
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80