apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-loadbalancer-service
  labels:
    app: app1-nginx
  annotations:
    #automatically adds annotation for a LB service similar to what it does for ingress LB
    external-dns.alpha.kubernetes.io/hostname: shubhams101.pecs-operations-dev.nl.lexis.com
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: app1-nginx
  ports:
    - port: 80
      targetPort: 80

   